export interface PulseAtlasPageEvent { path:string; }
const endpoint=process.env.NEXT_PUBLIC_PULSEATLAS_ENDPOINT;
const writeKey=process.env.NEXT_PUBLIC_PULSEATLAS_WRITE_KEY;
const enabled=Boolean(endpoint&&writeKey);
function browserId(storage:Storage,key:string,prefix:string){let value=storage.getItem(key);if(!value){value=`${prefix}_${crypto.randomUUID()}`;storage.setItem(key,value)}return value}
const staticPaths=new Set(["/","/models","/pricing","/developers","/tools/batch","/tools/cost","/tools/memory","/tools/speed","/tools/tokens-words","/app/overview","/app/projects","/app/runs","/app/usage","/app/cost-lab","/app/integrations","/app/budgets","/app/api-keys","/app/team","/app/settings","/app/billing","/app/audit","/app/finops","/app/findings","/app/route-lab","/app/experiments","/admin"]);
export function redactedPulseAtlasPath(rawPath:string){const path=rawPath.split("?")[0].split("#")[0]||"/";if(path.startsWith("/app/projects/"))return"/app/projects/:project";if(path.startsWith("/app/runs/"))return"/app/runs/:run";if(path.startsWith("/admin/"))return"/admin/:section";return staticPaths.has(path)?path:"/other"}
export function buildPageEvent(path:string){return{id:`evt_${crypto.randomUUID()}`,schemaVersion:1,organizationId:"portfolio_primary",projectId:"proj_token_intelligence",projectSlug:"token-intelligence",environment:(process.env.NEXT_PUBLIC_PULSEATLAS_ENVIRONMENT??"production"),eventName:"page_view",eventCategory:"page",occurredAt:new Date().toISOString(),anonymousId:browserId(localStorage,"ti_pa_aid","anon"),sessionId:browserId(sessionStorage,"ti_pa_sid","session"),properties:{path:redactedPulseAtlasPath(path)}}}
export async function trackPulseAtlasPage(path:string){if(!enabled||!endpoint||!writeKey)return false;try{await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json","x-pulseatlas-write-key":writeKey},body:JSON.stringify(buildPageEvent(path)),keepalive:true});return true}catch{return false}}
