import type { Metadata } from "next";
export const metadata: Metadata = { title: "Plans" };
const plans = [
  { name: "Free", price: "$0", audience: "Explore and plan", features: ["Local token calculator", "Full model pricing table", "Cost Lab", "Tokens ↔ words", "GPU RAM & speed tools"] },
  { name: "Pro", price: "$15/mo", audience: "Individual builders", features: ["Saved Cost Lab scenarios", "Personal API keys", "Prompt variant comparisons", "CSV/JSON exports", "MCP integration"] },
  { name: "Team", price: "$30/user/mo", audience: "Engineering teams", features: ["Shared projects", "Budgets & alerts", "Team API keys", "Usage analytics", "Role-based access"] },
  { name: "Enterprise", price: "Custom", audience: "Governed AI estates", features: ["SSO / SCIM", "Audit logs", "Policy engine", "Gateway & BYOK", "SIEM / dedicated deployment"] },
];
export default function PricingPage() { return <main className="page-shell shell"><section className="page-hero"><p className="eyebrow">Product packaging</p><h1>Keep planning free. Charge for operational control.</h1><p>The public calculator remains an acquisition surface. Paid tiers are designed around saved work, API/MCP access, team governance, and enterprise AI FinOps—not basic token counting.</p></section><section className="plan-grid">{plans.map((plan) => <article key={plan.name} className="plan-card"><div><p className="eyebrow">{plan.audience}</p><h2>{plan.name}</h2><strong className="plan-price">{plan.price}</strong></div><ul>{plan.features.map((feature) => <li key={feature}>{feature}</li>)}</ul><span className="plan-status">{plan.name === "Free" ? "Available now" : "Billing activation next"}</span></article>)}</section><section className="tool-card docs-section"><p className="eyebrow">Subscription implementation</p><h2>Billing is intentionally not fake.</h2><p>The product tiers and entitlement boundaries are now defined, but paid checkout is not enabled until a billing account is connected. The production implementation should create Stripe products/prices, Checkout, webhooks, customer portal, subscription state, and entitlement checks rather than sending users to a placeholder purchase flow.</p></section></main>; }
