import Link from "next/link";
import type { ReactNode } from "react";
import { Money, SourceBadge, StatusBadge } from "@/components/app-ui";

type OverviewData = Awaited<ReturnType<typeof import("@/lib/admin/data")["getAdminOverviewData"]>>;

export const adminSections = [
  ["/admin", "Mission control"], ["/admin/users", "Users"], ["/admin/organizations", "Organizations"], ["/admin/subscriptions", "Subscriptions"], ["/admin/revenue", "Revenue"], ["/admin/usage", "Usage"], ["/admin/finops", "AI FinOps"], ["/admin/platform-costs", "Platform costs"], ["/admin/providers", "Providers"], ["/admin/system", "System"], ["/admin/integrations", "Integrations"], ["/admin/audit", "Admin audit"], ["/admin/release", "Release readiness"],
] as const;

export function AdminShell({ children, role }: { children: ReactNode; role: string }) {
  return <div className="admin-frame"><aside className="admin-sidebar"><Link href="/admin" className="app-brand"><span className="app-brand__mark"><span>TI</span></span><span className="app-brand__copy"><strong>Token Intelligence</strong><small>Platform operations</small></span></Link><span className="admin-role">Platform · {role.replaceAll("_", " ")}</span><nav>{adminSections.map(([href, label]) => <Link href={href} key={href}>{label}</Link>)}</nav><Link href="/app/overview" className="admin-back">← Customer workspace</Link></aside><main className="admin-main">{children}</main></div>;
}

function Card({ label, value, detail }: { label: string; value: ReactNode; detail?: string }) { return <article className="admin-card"><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</article>; }

export function AdminOverview({ data }: { data: OverviewData }) {
  const health = Object.entries(data.health).filter(([key]) => ["database", "auth", "billing", "credentialVault", "github", "mcp"].includes(key));
  return <><header className="admin-header"><div><span className="app-kicker"><span className="app-kicker__dot" />Platform operations</span><h1>Business and infrastructure, in one view.</h1><p>Measured facts are separated from unavailable financial inputs. No missing cost or revenue is represented as zero.</p></div><SourceBadge source="real_time_snapshot" /></header><section className="admin-grid"><Card label="Registered users" value={String(data.users.total)} detail={`${data.users.today} today · ${data.users.sevenDays} in 7d`} /><Card label="Organizations" value={String(data.organizations.total)} detail="Platform-wide count" /><Card label="Active subscriptions" value={String(data.subscriptions.active)} detail={`${data.subscriptions.trialing} trialing · ${data.subscriptions.evidence.replaceAll("_", " ")}`} /><Card label="Runs / 30 days" value={String(data.usage.runs)} detail={`${data.usage.successfulRuns} successful · ${data.usage.failedRuns} failed`} /><Card label="Known AI cost" value={<Money value={data.usage.knownAiCostUsd} />} detail={`${data.usage.unknownAiCostCount} unknown-cost calls`} /><Card label="Platform cost" value={<Money value={data.economics.knownPlatformCostUsd} />} detail={data.economics.costCoverage.replaceAll("_", " ")} /></section><section className="admin-panel"><h2>Operational health</h2><div className="admin-statuses">{health.map(([name, status]) => <div key={name}><span>{name}</span><StatusBadge status={String(status)} /></div>)}</div></section><section className="admin-panel"><h2>Registration intelligence</h2><div className="admin-registration"><Card label="Today" value={String(data.users.today)} /><Card label="Yesterday" value={String(data.users.yesterday)} /><Card label="7 days" value={String(data.users.sevenDays)} /><Card label="30 days" value={String(data.users.thirtyDays)} /></div><p className="admin-note">A registration is the first creation of a Token Intelligence user, never a login.</p></section></>;
}

export function AdminSection({ title, description, rows, data }: { title: string; description: string; rows: Record<string, unknown>[]; data: OverviewData }) {
  const columns = rows[0] ? Object.keys(rows[0]).slice(0, 7) : [];
  return <><header className="admin-header"><div><span className="app-kicker"><span className="app-kicker__dot" />Platform operations</span><h1>{title}</h1><p>{description}</p></div><SourceBadge source={rows.length ? "provider_measured" : "unavailable"} /></header><section className="admin-grid"><Card label="Registrations / 30d" value={String(data.users.thirtyDays)} /><Card label="Runs / 30d" value={String(data.usage.runs)} /><Card label="Known AI cost" value={<Money value={data.usage.knownAiCostUsd} />} /><Card label="Revenue" value={<Money value={data.economics.revenueUsd} />} detail="Unavailable until Stripe evidence is synced" /></section><section className="admin-panel"><h2>{title} records</h2>{rows.length ? <div className="admin-table-wrap"><table><thead><tr>{columns.map((column) => <th key={column}>{column.replaceAll(/([A-Z])/g, " $1")}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={String(row.id ?? i)}>{columns.map((column) => <td key={column}>{render(row[column])}</td>)}</tr>)}</tbody></table></div> : <div className="empty-state"><div className="empty-state__icon">TI</div><div><h3>No measured records yet</h3><p>This surface intentionally shows unavailable rather than fabricated data. Connect the relevant provider or import an evidence-backed cost file.</p></div></div>}</section></>;
}
function render(value: unknown): ReactNode { if (value === null || value === undefined) return "—"; if (value instanceof Date) return value.toISOString().slice(0, 10); if (typeof value === "object") return "[metadata]"; return String(value); }
