import * as z from "zod/v4";

const evidenceTypeSchema = z.enum(["measured_before_after", "historical_observation", "modeled_estimate", "unknown"]);
const qualityGateSchema = z.enum(["passed", "failed", "not_run"]);
const nullableTokens = z.number().nonnegative().nullable();
const optionalNullableNumber = z.number().nonnegative().nullable().optional();
const optionalStrings = z.array(z.string().min(1)).max(100).optional();

export const portfolioRequestSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("output_reduction"),
    candidate: z.object({
      id: z.string().min(1),
      label: z.string().optional(),
      reducerVersion: z.string().nullable().optional(),
      measurementScope: z.enum(["payload_only", "full_session"]),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      sampleSize: z.number().int().nonnegative(),
      baselineTokens: nullableTokens,
      deliveredTokens: nullableTokens,
      retryTokens: optionalNullableNumber,
      reducerOverheadTokens: optionalNullableNumber,
      requiredSignals: optionalStrings,
      preservedSignals: optionalStrings,
      fallbackReason: z.string().nullable().optional(),
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("repository_context"),
    candidate: z.object({
      id: z.string().min(1),
      label: z.string().optional(),
      strategyVersion: z.string().nullable().optional(),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      indexState: z.enum(["fresh", "stale", "unknown", "not_applicable"]),
      sampleSize: z.number().int().nonnegative(),
      baselineSessionTokens: nullableTokens,
      candidateSessionTokens: nullableTokens,
      fallbackReadTokens: optionalNullableNumber,
      indexingSetupMs: optionalNullableNumber,
      retrievalLatencyMs: optionalNullableNumber,
      requiredEvidenceRefs: optionalStrings,
      returnedEvidenceRefs: optionalStrings,
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("response_density"),
    candidate: z.object({
      id: z.string().min(1),
      label: z.string().optional(),
      policyVersion: z.string().nullable().optional(),
      level: z.enum(["readable", "dense", "extreme"]),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      sampleSize: z.number().int().nonnegative(),
      baselineOutputTokens: nullableTokens,
      candidateOutputTokens: nullableTokens,
      baselineSessionTokens: nullableTokens,
      candidateSessionTokens: nullableTokens,
      instructionOverheadTokens: optionalNullableNumber,
      retryTokens: optionalNullableNumber,
      requiredPreservationClasses: optionalStrings,
      preservedClasses: optionalStrings,
      persistenceVerified: z.boolean().optional(),
      baselineClarificationTurns: optionalNullableNumber,
      candidateClarificationTurns: optionalNullableNumber,
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("structured_encoding"),
    candidate: z.object({
      id: z.string().min(1),
      format: z.string().min(1),
      formatVersion: z.string().nullable().optional(),
      measurementScope: z.enum(["payload_only", "full_session"]),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      fidelityGate: z.enum(["verified", "failed", "not_run"]),
      sampleSize: z.number().int().nonnegative(),
      baselinePayloadTokens: nullableTokens,
      encodedPayloadTokens: nullableTokens,
      baselineSessionTokens: optionalNullableNumber,
      candidateSessionTokens: optionalNullableNumber,
      formatInstructionTokens: optionalNullableNumber,
      decodeRepairTokens: optionalNullableNumber,
      retryTokens: optionalNullableNumber,
      requiredFields: optionalStrings,
      preservedFields: optionalStrings,
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("semantic_cache"),
    candidate: z.object({
      id: z.string().min(1),
      cacheMode: z.enum(["exact", "semantic"]),
      cacheVersion: z.string().nullable().optional(),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      freshness: z.enum(["fresh", "stale", "unknown"]),
      isolationGate: z.enum(["verified", "failed", "not_run"]),
      sampleSize: z.number().int().nonnegative(),
      baselineSessionTokens: nullableTokens,
      candidateSessionTokens: nullableTokens,
      lookupOverheadTokens: optionalNullableNumber,
      validationTokens: optionalNullableNumber,
      falseHitRecoveryTokens: optionalNullableNumber,
      providerFallbackTokens: optionalNullableNumber,
      observedHits: z.number().int().nonnegative(),
      observedMisses: z.number().int().nonnegative(),
      observedFalseHits: z.number().int().nonnegative(),
      maxFalseHitRate: z.number().min(0).max(1).optional(),
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("context_compression"),
    candidate: z.object({
      id: z.string().min(1),
      compressorVersion: z.string().nullable().optional(),
      measurementScope: z.enum(["payload_only", "full_session"]),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      cachePrefixGate: z.enum(["preserved", "changed", "not_applicable", "not_run"]),
      sampleSize: z.number().int().nonnegative(),
      baselineContextTokens: nullableTokens,
      deliveredContextTokens: nullableTokens,
      baselineSessionTokens: optionalNullableNumber,
      candidateSessionTokens: optionalNullableNumber,
      auxiliaryModelInputTokens: optionalNullableNumber,
      auxiliaryModelOutputTokens: optionalNullableNumber,
      recoveryTokens: optionalNullableNumber,
      retryTokens: optionalNullableNumber,
      compressionLatencyMs: optionalNullableNumber,
      requiredEvidenceRefs: optionalStrings,
      preservedEvidenceRefs: optionalStrings,
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("prompt_cache_economics"),
    candidate: z.object({
      id: z.string().min(1),
      policyVersion: z.string().nullable().optional(),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      cacheAccountingGate: z.enum(["verified", "failed", "not_run"]),
      sampleSize: z.number().int().nonnegative(),
      baselineCostUsd: z.number().nonnegative().nullable(),
      candidateCostUsd: z.number().nonnegative().nullable(),
      cacheControlOverheadCostUsd: optionalNullableNumber,
      fallbackCostUsd: optionalNullableNumber,
      baselineLogicalTokens: optionalNullableNumber,
      candidateLogicalTokens: optionalNullableNumber,
      cacheReadTokens: optionalNullableNumber,
      cacheWriteTokens: optionalNullableNumber,
      fallbackTokens: optionalNullableNumber,
      stablePrefixRate: z.number().min(0).max(1).nullable().optional(),
      minimumStablePrefixRate: z.number().min(0).max(1).optional(),
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("routing_economics"),
    candidate: z.object({
      id: z.string().min(1),
      policyVersion: z.string().nullable().optional(),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      routeProvenanceGate: z.enum(["verified", "failed", "not_run"]),
      sampleSize: z.number().int().nonnegative(),
      baselineCostUsd: z.number().nonnegative().nullable(),
      candidateCostUsd: z.number().nonnegative().nullable(),
      routingOverheadCostUsd: optionalNullableNumber,
      fallbackCostUsd: optionalNullableNumber,
      baselineTokens: optionalNullableNumber,
      candidateTokens: optionalNullableNumber,
      fallbackTokens: optionalNullableNumber,
      baselineRoute: z.string().nullable().optional(),
      resolvedRoutes: optionalStrings,
      requiredExactRoute: z.boolean().optional(),
      silentSubstitutionObserved: z.boolean().optional(),
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("budget_control"),
    candidate: z.object({
      id: z.string().min(1),
      policyVersion: z.string().nullable().optional(),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      enforcementGate: z.enum(["verified", "failed", "not_run"]),
      sampleSize: z.number().int().nonnegative(),
      budgetLimitUsd: z.number().nonnegative(),
      baselineCostUsd: z.number().nonnegative().nullable(),
      candidateCostUsd: z.number().nonnegative().nullable(),
      controlPlaneOverheadCostUsd: optionalNullableNumber,
      baselineSessionTokens: optionalNullableNumber,
      candidateSessionTokens: optionalNullableNumber,
      hardLimitBreaches: z.number().int().nonnegative().optional(),
      policyBypasses: z.number().int().nonnegative().optional(),
      requiredWorkDenied: z.number().int().nonnegative().optional(),
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("persistent_memory"),
    candidate: z.object({
      id: z.string().min(1),
      memoryVersion: z.string().nullable().optional(),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      freshness: z.enum(["fresh", "stale", "unknown"]),
      provenanceGate: z.enum(["verified", "failed", "not_run"]),
      isolationGate: z.enum(["verified", "failed", "not_run"]),
      sampleSize: z.number().int().nonnegative(),
      baselineSessionTokens: nullableTokens,
      candidateSessionTokens: nullableTokens,
      memoryWriteTokens: optionalNullableNumber,
      memoryIndexTokens: optionalNullableNumber,
      memoryRetrievalTokens: optionalNullableNumber,
      recoveryTokens: optionalNullableNumber,
      requiredEvidenceRefs: optionalStrings,
      retrievedEvidenceRefs: optionalStrings,
      contradictoryMemoryCount: z.number().int().nonnegative().optional(),
      staleMemoryCount: z.number().int().nonnegative().optional(),
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("orchestration_efficiency"),
    candidate: z.object({
      id: z.string().min(1),
      orchestrationVersion: z.string().nullable().optional(),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      provenanceGate: z.enum(["verified", "failed", "not_run"]),
      sampleSize: z.number().int().nonnegative(),
      baselineSessionTokens: nullableTokens,
      candidateWorkerTokens: nullableTokens,
      coordinatorTokens: optionalNullableNumber,
      handoffTokens: optionalNullableNumber,
      retryTokens: optionalNullableNumber,
      fallbackTokens: optionalNullableNumber,
      baselineCostUsd: optionalNullableNumber,
      candidateWorkerCostUsd: optionalNullableNumber,
      coordinatorCostUsd: optionalNullableNumber,
      fallbackCostUsd: optionalNullableNumber,
      observedMaxFanout: z.number().int().nonnegative().optional(),
      maxAllowedFanout: z.number().int().positive().optional(),
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
  z.object({
    kind: z.literal("optimizer_plan"),
    candidate: z.object({
      id: z.string().min(1),
      components: z.array(z.object({
        id: z.string().min(1),
        familyKey: z.string().min(1),
        claimClass: z.enum(["token_reduction_candidate", "mixed_token_and_cost_candidate", "cost_reduction_only"]),
        individualClaimable: z.boolean(),
        individualSavingsPct: z.number().nonnegative().nullable().optional(),
      }).strict()).min(1).max(50),
      evidenceType: evidenceTypeSchema,
      qualityGate: qualityGateSchema,
      sampleSize: z.number().int().nonnegative(),
      baselineSessionTokens: nullableTokens,
      candidateSessionTokens: nullableTokens,
      baselineCostUsd: optionalNullableNumber,
      candidateCostUsd: optionalNullableNumber,
      evidenceSource: z.string().nullable().optional(),
    }).strict(),
  }).strict(),
]);

export const portfolioAnalysisInput = z.object({
  requests: z.array(portfolioRequestSchema).min(1).max(50),
  minimumSampleSize: z.number().int().min(1).max(100).default(5),
}).strict();
